### ISSUE TITLE
Просьба протестировать модуль на тестовом контуре ЕСИА

### ISSUE THREAD

**Issue by DarkScorpion** [yetihead/esia#3]
Установили модуль в нашу систему и используем самоподписной сертификат одобренный ЕСИА.
Но возникает ошибка "неправильная подпись". Хотелось узнать, актуален ли модуль на данный момент.
Тестовый контур: https://esia-portal1.test.gosuslugi.ru

**Comment by yetihead** [comment]
> Установили модуль в нашу систему и используем самоподписной сертификат одобренный ЕСИА.
> Но возникает ошибка "неправильная подпись". Хотелось узнать, актуален ли модуль на данный момент.
> Тестовый контур: https://esia-portal1.test.gosuslugi.ru

К сожалению, не могу это сделать. В тестовую среду можно попасть заполнив заявку от организации. Писал модуль когда была учетка и сертификат от организации, но сейчас этого нет.
